name: juju-spell
base: core22
adopt-info: juju-spell
# version: "0.1"
summary: collects an operates at several clouds at the same time
description: |
  Connects to multiple clouds and allows to run commands at the same time.

grade: devel
confinement: devmode

apps:
  juju-spell:
    command: bin/juju_spell
    plugs: [ network, network-control, ssh-keys ]
    environment:
      JUJUSPELLSDIR: $SNAP_DATA/

parts:
  juju-spell:
    plugin: python
    python-requirements: [ ./requirements.txt ]
    source: .
    stage-packages:
      - git
    override-build: |
      snapcraftctl build
      echo "Version: $(python3 setup.py --version)"
      snapcraftctl set-version "$(python3 setup.py --version)"
